### ISSUE TITLE
Mouse cursor not available 

### ISSUE THREAD

**Issue by urandom** [jurialmunkey/skin.arctic.zephyr#12]
When a mouse is connected, there is no visible cursor, even though the system reacts to mouse events.

This is with zephyr v1.6.1, available from the official repository

**Comment by jurialmunkey** [comment]
Skin doesn't support mouse. Turn off mouse input at: 
Settings > System > Input Devices > Enable mouse and touchscreen support

**Comment by urandom** [comment]
Besides the missing cursor, the mouse seems to interact with the skin just fine (if you are lucky enough to actually find a control in the blind). You might not be able to exit a menu, but at least a mouse could be useful for quickly interacting with an already playing movie. Which is where a simple cursor would be quite useful
