### ISSUE TITLE
Font size for a screensaver

### ISSUE THREAD

**Issue by vdb86** [jurialmunkey/skin.arctic.zephyr#16]
Hi jurialmunkey, I've made a screensaver for Kodi, unfortunately addons can't use their own Fonts and we have to rely on skins to provide them.
Would you please add a font size to Arctic Zephyr?
The name doesn't matter, but I would prefer something like clock.
The font size should be 130.
If you need any more information please let me know.
Thank you for your help!

**Comment by jurialmunkey** [comment]
Sorry I missed your PR. Just merged it. :)

**Comment by vdb86** [comment]
Thank you!
When you get a chance Eminence needs a font size too :)
