### ISSUE TITLE
No Programme Information window in EPG view

### ISSUE THREAD

**Issue by thmang82** [jurialmunkey/skin.arctic.zephyr#26]
Hey,

I am running Kodi Jarvis Beta 4 with OpenElec on an Odroid C1+ (Amlogic S805)

When in EPG view, hitting the ok button does not open the "Programme Information" window. Same applies when opening the context menu via "c" button on the keyboard and trying to open the programme information form there. The windows just does not appear, nothing happens :-(
This only happens in Arctic Zephyr. It works in in any other skin, even in mods like Arctic.Zephyr.Braz.

The problem was there in any Jarvis version I tried (Alpha 4, Beta 2, Beta 4).
I am not quite sure if this is a general issue with Arctic Zephyr and Jarvis or if it's related to the Amlogic S805 (as there was a note in Kodi 3 release notes that there were improvements for that platform).

Hope this can be fixed. I really like the skin. It's very modern looking and incredible fast.

Best regards,
Thomas

**Comment by jurialmunkey** [comment]
Yeah there were changes to a few dialogs between Isengard and Jarvis. Just hadn't got around to this one yet. Should be fixed now.
