### ISSUE TITLE
Cannot Create Shortcut to Music Addons

### ISSUE THREAD

**Issue by saskwatch** [jurialmunkey/skin.arctic.zephyr#27]
ANDROID: Customize home menu allows me to create the shortcut for music addons, but it brings up the picker for thumbnails vs list, etc.  Once I get pass the pop-up, the addons show up, but it won't allow me to pick an addon.

MAC: Customize home menu allows me to create the shortcut for music addons, but it does not show up on the home menu.

**Comment by jurialmunkey** [comment]
Skinshortcuts issue.
