### ISSUE TITLE
Duration not shown correctly

### ISSUE THREAD

**Issue by Guig87** [jurialmunkey/skin.arctic.zephyr#29]
Hi,

I really love this skin.
I've found a little annoying bug. The duration of the film (retrieved from tmdb, etc.) is not correctly shown: Only the number of hours is shown (with the label "min" after).

For example, for a film whose duration is 2h35min, It is shown "2min". Same for 1h56min => "1min".

Can you help me?

Thanks

Please note that this problem only appears on this skin (for example it works perfectly on eminence 2.0, confluence...)

**Comment by jurialmunkey** [comment]
Do you have a screenshot?

**Comment by Guig87** [comment]
Hi,

The problem seems to be solved. Sorry for the disturbance!
