### ISSUE TITLE
[Evolution] home menu item

### ISSUE THREAD

**Issue by alexandre-lg** [jurialmunkey/skin.arctic.zephyr#3]
Hello,

In french, some elements from the home screen are split (screenshot 1) but when I select them, they are extended (screenshot 2). It's possible to extende them by default?

Thanks for your works and good luck for the next step.
![screenshot000](https://cloud.githubusercontent.com/assets/3471351/6358261/b0b1f072-bc6a-11e4-887b-2df31e8ea154.png)
![screenshot001](https://cloud.githubusercontent.com/assets/3471351/6358262/b0b5f9ce-bc6a-11e4-90de-c2b7d9827da9.png)

**Comment by jurialmunkey** [comment]
Its because the focussed item scrolls when selected. You will have to set a label for that item that is shorter.

**Comment by alexandre-lg** [comment]
Ok, but "PARAMETRES" contains 10 letters and "PARAMETR..." contains 11 letters, it's curious to cut a shorter string.

**Comment by jurialmunkey** [comment]
Its controlled by kodi based upon the pixel width of the label. An ellipsis (...) has less pixel width than the two letters that are cut.

**Comment by alexandre-lg** [comment]
Ok, thanks !
