### ISSUE TITLE
No text on PVR Recording window

### ISSUE THREAD

**Issue by jefvanleeuwen** [jurialmunkey/skin.arctic.zephyr#30]
Complimnets for the Skin.arctic.zephyr, but  I have a issue with PVR recordings. The confirmation for recordings in Skin.arctic.zephyr stays empty? See screen prints for both, I traced it back to windowed 603 in RecordPref.xml (I think...).

And also the Notification when recording or delete recordings is wrong, I thimk it is the previous Recording I used....

It is a Main issue and the (end)users in my family and also my friends are confused using the system.
Is there a work-around (insert text manually) to fix it now.....and in my system....

Confluence:
![image](https://cloud.githubusercontent.com/assets/12883650/12076333/d453cf40-b1a7-11e5-88fb-edb3e6dad302.png)

Skin.arctic.zephyr:
![image](https://cloud.githubusercontent.com/assets/12883650/12076383/2a1995ac-b1aa-11e5-9261-a8bd2efeee4c.png)

**Comment by jurialmunkey** [comment]
That's because NextPVR reuses WMCPVR windows but the controls dont match. I thought there was a fix for this posted on the A:Z forum somewhere.
