### ISSUE TITLE
No video shown in background in DialogueVideoInfo.xml window

### ISSUE THREAD

**Issue by hmiah101** [jurialmunkey/skin.arctic.zephyr#31]
Hi JM,

I've noticed that there is a plain background displayed on the DialogueVideoInfo.xml window when there is a video playing in the background even though the option in:

Skin Settings> Background> Show now playing video in background

has been enabled. It works elsewhere throughout the skin and worked perfectly fine on version 2.0.0 of the skin in Isengard. 

Hope that helps and thank you for all your hard work on this awesome skin.

Running Kodi v16.0 “Jarvis” beta 4 (ARM)
Skin version: commit 68be797 from Github ('master' branch) (current).

**Comment by jurialmunkey** [comment]
I can't reproduce this. Works fine for me on Jarvis. Can you get a screenshot?
