### ISSUE TITLE
Missing Buttons in Add-On Info screen

### ISSUE THREAD

**Issue by Anthrax-Leprosy-Pi** [jurialmunkey/skin.arctic.zephyr#39]
Hey there jurialmonkey,

AWESOME skin! 
Only thing that nags me are the missing Buttons when trying to enable/disable or (un)install add-ons...
Am I missing something? Is this a design choice? 

Workaround is to temporarily switch to confluence...

regards
Anthrax

**Comment by perfectcolors** [comment]
Do you have Kiosk mode enabled?

**Comment by Anthrax-Leprosy-Pi** [comment]
Blood just shot right up my head - I'm blushing...

Kiosk-Mode always sounded so much fun - little did I realize that this might be the culprit ;-)
Kind of makes sense - hehe...

Thank you so much!
Anthrax

PS: great skin, great community
