### ISSUE TITLE
[Bug] Commits from Feb 24, 2015

### ISSUE THREAD

**Issue by alexandre-lg** [jurialmunkey/skin.arctic.zephyr#4]
Hello,

Since commits from 24th feb, I've a bug when I want to edit home menu (see in screen).

Thanks for your works and good luck for the next step.

![screenshot003](https://cloud.githubusercontent.com/assets/3471351/6358349/209139d4-bc6b-11e4-9ed1-c520c7afe0f3.png)

**Comment by jurialmunkey** [comment]
What is the bug???

**Comment by alexandre-lg** [comment]
Sorry, I am just idiot ^^
