### ISSUE TITLE
OSMC Kodi 16.1 Crashes

### ISSUE THREAD

**Issue by bishamontn** [jurialmunkey/skin.arctic.zephyr#42]
Impossible to work with your theme in OSMC last release. All details in OSMC forum.

https://discourse.osmc.tv/t/kodi-crash-loop-after-update/15597/14

It's a pity your theme is awesome.

**Comment by MaciejJanyska** [comment]
+1

**Comment by rimonhanna** [comment]
I also hope this would be fixed, I loved this theme!

**Comment by EdKo66** [comment]
I too hope it will be fixed soon. I hate the skin I use at the moment.

**Comment by jesuisbaatman** [comment]
I own raspberry pi 2 with osmc last version 16.1 (2016.06.2) and and I would like install arctic zephyr

and I heard that there were risk of bootloop,
you can comfirmed me if i can install it on safe handling ?
thank you
