### ISSUE TITLE
[Bug] Widget showing but non defined

### ISSUE THREAD

**Issue by alexandre-lg** [jurialmunkey/skin.arctic.zephyr#5]
Hello,

I've customized my home menu to set `none` on `Files` but the widget is displayed.

Thanks for your works and good luck for the next step.

**Comment by jurialmunkey** [comment]
Read the FAQ on first post of the thread.

**Comment by alexandre-lg** [comment]
Oh yes, sorry, I don't see the FAQ, thanks !
