### ISSUE TITLE
Auto update is unchecked at each boot

### ISSUE THREAD

**Issue by eSkRo32** [jurialmunkey/skin.arctic.zephyr#56]
Hi and thx for this Amazing skin! 
My favorite off all! 

However, i got an issue where, when i turn on the auto update and notification features
Well, upon boots or reboots, 
When going in addons and making the drop down menu appear, 
We clearely see that They unchecked themselves. 

So even if i check them Both again, 
And reboot, 
When i go back in addons 
and make the drop down menu appear, 
Both options are always unchecked.. 

So my addons never update.. 

Possible fix? 

Thx!

**Comment by jurialmunkey** [comment]
Not a skin issue. Kodi issue. Ask on appropriate section of kodi.tv forums
