### ISSUE TITLE
EPG / Channel List for Radio stations incomplete

### ISSUE THREAD

**Issue by hansworst24** [jurialmunkey/skin.arctic.zephyr#7]
Hi,

I'm hoping this is the right way to report a bug I'm seeing in this <marvelous> skin !!

I'm using a TVH backend for both Radio/TV Stations. The homescreen does not provide a seperate "Radio" shortcut, but by adding it manually it will redirect you to the default EPG Guide view. This view will only show the Radio Stations for which EPG information is available. Stations that do not have any EPG information are not listed. Nevertheless, if you select a station which has EPG information, and it is playing, you can do channelup/channeldown and the PVR backend will switch to another radio station, even the ones not listed in the EPG view.

Therefore, I think a small adaptation needs to be made to the "Radio" view, and also list Radio channels without EPG information.

I don't see this issue in the Aeon Nox or other skins... But for now your skin will remain my favourite for a long time as it is "just exactly right" in terms of simplicity, font size, color usage etc :-)

Thanks,
Frank

**Comment by jurialmunkey** [comment]
Radio works fine for me. Skins only control how to display content, they don't control what content is shown - that's handled by kodi. I have a feeling that you've accidentally changed the Channel Group from the side menu (the one you get by pressing back from the epg guide).

Also, you can add a Radio Channels view from home customisation dialog. 
Choose Shortcut > Radio > Channels

**Comment by hansworst24** [comment]
You're so right :) The Radio shortcut defaults to the EPG view when added to the Home screen, this view only shows channels with EPG info. The sub-menu Channels shows all channels. Strange that I overlooked that !! Many thanks :)
