### ISSUE TITLE
Android - Leia RC5 compatibility

### ISSUE THREAD

**Issue by MissonHxC** [jurialmunkey/skin.arctic.zephyr#86]
Leia RC5 Android came out on January 12, 2019.
After startup/database migration/etc. a popup informs you that Arctic Zephyr is incompatible with this Leia version and fallback to Estuary.

**Comment by ConiKost** [comment]
This should fix it https://github.com/jurialmunkey/skin.arctic.zephyr/pull/87

**Comment by MissonHxC** [comment]
I confirm, it works very well.

**Comment by jurialmunkey** [comment]
Merged to master.
