### ISSUE TITLE
Question: How to add "full screen" button in left side bar

### ISSUE THREAD

**Issue by berturion** [jurialmunkey/skin.arctic.zephyr#9]
Hello and thanks a lot for your amazing skin.
I think it's the best available for now.
I have a question though.
In confluence, before installing zephyr, when I open a Direct TV Channel (and opening music also), I had "full screen", "play", "pause", "stop" buttons on the left sidebar.
These buttons are very important for me because I have few controls from my TV remote control and in zephyr I can't find those. Maybe I can add them with your skin settings but I don't know how...
Maybe using kodi commands ? I don't know.
Thanks for your help.

**Comment by jurialmunkey** [comment]
Please ask questions about the skin on the forum. :)

**Comment by berturion** [comment]
OK, no problem.
